// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xneuralnetwork.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XNeuralnetwork_CfgInitialize(XNeuralnetwork *InstancePtr, XNeuralnetwork_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Nnio_BaseAddress = ConfigPtr->Nnio_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XNeuralnetwork_Start(XNeuralnetwork *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_AP_CTRL) & 0x80;
    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_AP_CTRL, Data | 0x01);
}

u32 XNeuralnetwork_IsDone(XNeuralnetwork *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XNeuralnetwork_IsIdle(XNeuralnetwork *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XNeuralnetwork_IsReady(XNeuralnetwork *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XNeuralnetwork_EnableAutoRestart(XNeuralnetwork *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_AP_CTRL, 0x80);
}

void XNeuralnetwork_DisableAutoRestart(XNeuralnetwork *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_AP_CTRL, 0);
}

u32 XNeuralnetwork_Get_return(XNeuralnetwork *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_AP_RETURN);
    return Data;
}
void XNeuralnetwork_Set_runNN_r(XNeuralnetwork *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_RUNNN_R_DATA, Data);
}

u32 XNeuralnetwork_Get_runNN_r(XNeuralnetwork *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_RUNNN_R_DATA);
    return Data;
}

void XNeuralnetwork_Set_setBais_r(XNeuralnetwork *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_SETBAIS_R_DATA, Data);
}

u32 XNeuralnetwork_Get_setBais_r(XNeuralnetwork *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_SETBAIS_R_DATA);
    return Data;
}

void XNeuralnetwork_Set_setWeight_r(XNeuralnetwork *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_SETWEIGHT_R_DATA, Data);
}

u32 XNeuralnetwork_Get_setWeight_r(XNeuralnetwork *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_SETWEIGHT_R_DATA);
    return Data;
}

u32 XNeuralnetwork_Get_input_r_BaseAddress(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE);
}

u32 XNeuralnetwork_Get_input_r_HighAddress(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_INPUT_R_HIGH);
}

u32 XNeuralnetwork_Get_input_r_TotalBytes(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XNEURALNETWORK_NNIO_ADDR_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE + 1);
}

u32 XNeuralnetwork_Get_input_r_BitWidth(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNEURALNETWORK_NNIO_WIDTH_INPUT_R;
}

u32 XNeuralnetwork_Get_input_r_Depth(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNEURALNETWORK_NNIO_DEPTH_INPUT_R;
}

u32 XNeuralnetwork_Write_input_r_Words(XNeuralnetwork *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XNEURALNETWORK_NNIO_ADDR_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XNeuralnetwork_Read_input_r_Words(XNeuralnetwork *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XNEURALNETWORK_NNIO_ADDR_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XNeuralnetwork_Write_input_r_Bytes(XNeuralnetwork *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XNEURALNETWORK_NNIO_ADDR_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XNeuralnetwork_Read_input_r_Bytes(XNeuralnetwork *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XNEURALNETWORK_NNIO_ADDR_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_INPUT_R_BASE + offset + i);
    }
    return length;
}

u32 XNeuralnetwork_Get_biasWeight_input_r_BaseAddress(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE);
}

u32 XNeuralnetwork_Get_biasWeight_input_r_HighAddress(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_HIGH);
}

u32 XNeuralnetwork_Get_biasWeight_input_r_TotalBytes(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE + 1);
}

u32 XNeuralnetwork_Get_biasWeight_input_r_BitWidth(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNEURALNETWORK_NNIO_WIDTH_BIASWEIGHT_INPUT_R;
}

u32 XNeuralnetwork_Get_biasWeight_input_r_Depth(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNEURALNETWORK_NNIO_DEPTH_BIASWEIGHT_INPUT_R;
}

u32 XNeuralnetwork_Write_biasWeight_input_r_Words(XNeuralnetwork *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XNeuralnetwork_Read_biasWeight_input_r_Words(XNeuralnetwork *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XNeuralnetwork_Write_biasWeight_input_r_Bytes(XNeuralnetwork *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XNeuralnetwork_Read_biasWeight_input_r_Bytes(XNeuralnetwork *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_HIGH - XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Nnio_BaseAddress + XNEURALNETWORK_NNIO_ADDR_BIASWEIGHT_INPUT_R_BASE + offset + i);
    }
    return length;
}

void XNeuralnetwork_InterruptGlobalEnable(XNeuralnetwork *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_GIE, 1);
}

void XNeuralnetwork_InterruptGlobalDisable(XNeuralnetwork *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_GIE, 0);
}

void XNeuralnetwork_InterruptEnable(XNeuralnetwork *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_IER);
    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_IER, Register | Mask);
}

void XNeuralnetwork_InterruptDisable(XNeuralnetwork *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_IER);
    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_IER, Register & (~Mask));
}

void XNeuralnetwork_InterruptClear(XNeuralnetwork *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XNeuralnetwork_WriteReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_ISR, Mask);
}

u32 XNeuralnetwork_InterruptGetEnabled(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_IER);
}

u32 XNeuralnetwork_InterruptGetStatus(XNeuralnetwork *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XNeuralnetwork_ReadReg(InstancePtr->Nnio_BaseAddress, XNEURALNETWORK_NNIO_ADDR_ISR);
}

