lappend pragmaStatus0 {pragma "PIPELINE" source "C:/Users/jespe/Desktop/Uni_Civil_9_Semester/Embedded_course/ERTS_final_project/HLS_project/../NN_Code/NN_Code/neuralnetwork_ccode.c" location "relu/relu_label1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "PIPELINE" source "C:/Users/jespe/Desktop/Uni_Civil_9_Semester/Embedded_course/ERTS_final_project/HLS_project/../NN_Code/NN_Code/neuralnetwork_ccode.c" location "runLayer/runLayer_label2" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'runLayer_label2' does not exist in function 'runLayer'. "}
lappend pragmaStatus2 {pragma "PIPELINE" source "C:/Users/jespe/Desktop/Uni_Civil_9_Semester/Embedded_course/ERTS_final_project/HLS_project/../NN_Code/NN_Code/neuralnetwork_ccode.c" location "softmax_lite/softmax_lite_loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "INLINE" source "C:/Users/jespe/Desktop/Uni_Civil_9_Semester/Embedded_course/ERTS_final_project/HLS_project/../NN_Code/NN_Code/neuralnetwork_ccode.c" location "getBias" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "INLINE" source "C:/Users/jespe/Desktop/Uni_Civil_9_Semester/Embedded_course/ERTS_final_project/HLS_project/../NN_Code/NN_Code/neuralnetwork_ccode.c" location "getWeight" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "INLINE" source "C:/Users/jespe/Desktop/Uni_Civil_9_Semester/Embedded_course/ERTS_final_project/HLS_project/../NN_Code/NN_Code/neuralnetwork_ccode.c" location "relu" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "INLINE" source "C:/Users/jespe/Desktop/Uni_Civil_9_Semester/Embedded_course/ERTS_final_project/HLS_project/../NN_Code/NN_Code/neuralnetwork_ccode.c" location "runLayer" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "LOOP_MERGE" source "C:/Users/jespe/Desktop/Uni_Civil_9_Semester/Embedded_course/ERTS_final_project/HLS_project/../NN_Code/NN_Code/neuralnetwork_ccode.c" location "runLayer/runLayer_Outerloop" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'LOOP_MERGE' cannot be applied: Label 'runLayer_Outerloop' does not exist in function 'runLayer'. "}
lappend pragmaStatus8 {pragma "LOOP_MERGE" source "C:/Users/jespe/Desktop/Uni_Civil_9_Semester/Embedded_course/ERTS_final_project/HLS_project/../NN_Code/NN_Code/neuralnetwork_ccode.c" location "runLayer/runLayer_outerloop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
